/* copy.js — every string on the site, by id.
   This is the file the pages read from. Edit it here, or on the page with
   ?edit=1 and click "Download copy.js" to regenerate it.

   {tokens} are filled per visitor: {first_name} {her_name} {goal} {goal_lower}
   {status} {time_since} {hardest_part} {issue_1} {issue_2} {outcome_1}
   {outcome_2} {promo_code}.
   [label](href) becomes a link.
   Prices and rebill terms are NOT here on purpose — they live in TIERS in
   offer.html so they cannot drift from what the checkout charges. */
window.COPY = {
  "age.legal": "By continuing you agree to our [Terms](#), [Privacy Policy](#) and [Subscription Terms](#).",
  "brand.wordmark": "Jamo Dating Protocols",
  "email.cta": "Send my plan",
  "email.eyebrow": "Plan ready",
  "email.foot": "Next: your name and hers",
  "email.h1": "Where should we send your plan?",
  "email.lede": "We'll email you a copy so you can come back to it. Your results open on the next screen either way.",
  "email.optin": "Also send me weekly tactics and updates. Separate from your plan — skip it and still continue.",
  "email.placeholder": "you@email.com",
  "email.privacy": "We don't sell your data and one click unsubscribes you. [Privacy Policy](#).",
  "foot.company": "Jamo Health Consulting · 82 Wendell Ave., Ste 100, Pittsfield, MA 01201, United States",
  "foot.links": "[Terms](#) · [Privacy](#) · [Subscription Terms](#)",
  "i:authority:attrib": "The Jamo Dating Protocols team",
  "i:authority:cta": "Continue",
  "i:authority:number": "51,000+",
  "i:authority:number_sub": "men have run this plan",
  "i:authority:quote": "You don't need to beg or chase. You need to change what she feels when your name comes up.",
  "i:authority:sources": "Built on published research into attachment and re-connection — [SOURCE 1](#), [SOURCE 2](#). Cite what you actually used.",
  "i:insight:body": "Trust and emotional distance aren't personality flaws — they're patterns, and patterns respond to a sequence. Your plan starts with the two you picked.",
  "i:insight:cta": "Continue",
  "i:insight:eyebrow": "Worth knowing",
  "i:insight:title": "Every one of those is trainable",
  "i:relief:body": "Wanting to {goal_lower} is not the hard part. Knowing the order to do things in is, and that is the whole of what your plan gives you.",
  "i:relief:cta": "Continue",
  "i:relief:eyebrow": "Worth knowing",
  "i:relief:title": "That's fixable — and faster than you think",
  "img.age0": "",
  "img.age1": "",
  "img.age2": "",
  "img.age3": "",
  "img.insight": "",
  "img.review1": "",
  "img.review2": "",
  "img.review3": "",
  "loader.h1": "Building your plan",
  "loader.phase1": "Mapping your situation",
  "loader.phase2": "Scoring her signals",
  "loader.phase3": "Selecting your modules",
  "loader.reviews_label": "What men say after week one",
  "loader.sub": "Based on your 11 answers",
  "modal.eyebrow": "One quick thing",
  "modal.no": "No",
  "modal.question": "Are you someone who finishes what you start?",
  "modal.yes": "Yes",
  "names.cta": "Continue",
  "names.eyebrow": "Last step",
  "names.h1": "Who is this plan for?",
  "names.label_her": "Her name",
  "names.label_you": "Your first name",
  "names.lede": "Both names go into your plan so the scripts read like something you'd actually send.",
  "names.placeholder_her": "Type her name",
  "names.placeholder_you": "Alex",
  "names.privacy": "Names stay on your plan. We never message anyone on your behalf.",
  "offer.badge": "Most men choose this",
  "offer.bump_d1": "The exact messages, scripted per situation.",
  "offer.bump_d2": "one time, added to this order.",
  "offer.bump_t": "Add: 30 Texts That Reopen the Conversation",
  "offer.cta": "Get my plan",
  "offer.cta_bar": "Get my plan",
  "offer.disclosure_head": "Your plan renews automatically.",
  "offer.disclosure_tail": "Cancel in one click from your account or any receipt — no email required. [Subscription Terms](#).",
  "offer.eyebrow": "Step 2 of 2",
  "offer.faq1_a#ambiguous": "Complicated usually means the rules keep changing and you are the one adapting. The plan starts by making your side predictable, because that is the only half you control.",
  "offer.faq1_a#default": "In the details it will be. The sequence is not built on one story — it is built on the order things have to happen in, and that order holds across most of them.",
  "offer.faq1_a#distance": "No — silence on its own reads as sulking, and she has seen that before. What matters is what you do with the time and what she sees when she looks. Most of the plan is the second part.",
  "offer.faq1_a#moveon": "No. You said move on, so the plan moves on — no reopening scripts, no strategy for making her miss you. It is about getting your sleep, your attention and your weeks back.",
  "offer.faq1_a#reconcile": "Most are. The sequence does not assume a clean break — it assumes you have limited contact and limited credit with her, and it starts by rebuilding both.",
  "offer.faq1_a#reconcile_fresh": "The opposite. The first two weeks are the ones most men spend making it worse, because it is when the urge to explain yourself is strongest. The plan opens with what to do while it is still raw.",
  "offer.faq1_a#rekindle": "Often, yes — flat is usually a pattern rather than a verdict, and patterns respond to a sequence. What nobody can tell you is whether she wants the same thing, and the plan is honest about testing that early.",
  "offer.faq1_a#together": "Yes, and it is easier from here than after a breakup. Nothing asks you to manufacture distance or play games with someone you share a life with — it works on what changed in the day to day, because that is usually where it went.",
  "offer.faq1_q#ambiguous": "My situation doesn't really fit a category.",
  "offer.faq1_q#default": "What if my situation is different?",
  "offer.faq1_q#distance": "Isn't this just going quiet on her?",
  "offer.faq1_q#moveon": "Will this try to talk me into getting her back?",
  "offer.faq1_q#reconcile": "My situation is messier than the quiz allowed for.",
  "offer.faq1_q#reconcile_fresh": "It only just ended — is it too early to start?",
  "offer.faq1_q#rekindle": "Can you get it back once it's gone flat?",
  "offer.faq1_q#together": "We're still together — is this for us?",
  "offer.faq2_a#ambiguous": "Then at least you stop living in the gap. Deciding gets much easier once you are sleeping and not checking her profile — that is what the first two weeks are for.",
  "offer.faq2_a#default": "It might not. Anything involving another person cannot be promised, and you should be suspicious of anyone who does. What is in your control is doing the right things in the right order rather than too early, which is where most of this goes wrong.",
  "offer.faq2_a#distance": "Unknowable, honestly — that depends on her. What is in your control is being worth noticing when she does look, and that starts in week one.",
  "offer.faq2_a#moveon": "You might, and that is allowed. The early work is the same either way, and you will be in a far better position to make that call in six weeks than you are tonight.",
  "offer.faq2_a#reconcile": "That is possible, and nobody can promise you otherwise. What this stops is another three months of messages that make a reply less likely, and it gives you work that is worth doing either way.",
  "offer.faq2_a#reconcile_fresh": "Then you find that out in week one instead of month three. Nothing in the early work depends on her replying — it is the part that decides whether a reply, if it comes, goes anywhere.",
  "offer.faq2_a#rekindle": "Then you will see it sooner rather than after another six months of hoping. That is not the answer you want, but knowing it early is worth more than a plan that pretends otherwise.",
  "offer.faq2_a#together": "Your call. Nothing in the plan needs a conversation about the plan. Most of week one is things she will notice without being told, which is generally the better order.",
  "offer.faq2_q#ambiguous": "What if it never resolves either way?",
  "offer.faq2_q#default": "What if it doesn't work?",
  "offer.faq2_q#distance": "How long before she notices?",
  "offer.faq2_q#moveon": "What if I change my mind?",
  "offer.faq2_q#reconcile": "What if she never replies?",
  "offer.faq2_q#reconcile_fresh": "What if she doesn't reply?",
  "offer.faq2_q#rekindle": "What if she's already checked out?",
  "offer.faq2_q#together": "Do I have to tell her I'm doing this?",
  "offer.faq3_a": "One click in your account, or the link in any receipt. Saying it plainly here lowers refunds and chargebacks more than it costs you.",
  "offer.faq3_q": "How do I cancel?",
  "offer.faq_h2": "Before you decide",
  "offer.h1": "Your {goal_lower} plan, {first_name}",
  "offer.includes_h2": "What you get today",
  "offer.promo": "Promo {promo_code} applied — {discount}% off your first term",
  "offer.tick1": "Your full plan, sequenced day by day",
  "offer.tick3": "The confidence track you asked to include",
  "offer.tick4": "Sleep and energy reset alongside week 1",
  "offer.tier1_blurb": "Enough to run the first reset and the opening message.",
  "offer.tier2_blurb": "The full sequence, with enough runway for the conversation to actually restart.",
  "offer.tier3_blurb": "For long relationships, where rebuilding takes more than one season.",
  "offer.timer_label": "Your discount holds for",
  "plan.cta": "Get my plan",
  "plan.cta_note": "Your {discount}% discount is applied on the next screen.",
  "plan.eyebrow": "Plan ready",
  "plan.fact1_label": "Status",
  "plan.fact2_label": "Goal",
  "plan.fact3_label": "Time since",
  "plan.h1": "{first_name}, here's how you reopen things with {her_name}",
  "plan.lede": "You said the hardest part is “{hardest_part}”. That's where week one starts — not with a message to her.",
  "plan.meter1": "Attraction",
  "plan.meter2": "Her interest",
  "plan.meter3": "Your headspace",
  "plan.meters_h2": "Where you are, where this goes",
  "plan.meters_note": "Illustrative — not a predicted outcome",
  "plan.meters_range": "Now → 30 days",
  "plan.module1_meta": "Module 2 · 6 days · rebuilding what broke",
  "plan.module2_meta": "Module 4 · 8 days · closing the gap",
  "plan.module3_meta": "Module 6 · day 12",
  "plan.module3_t": "The first message, written for your situation",
  "plan.module4_meta": "Runs alongside from day 1",
  "plan.module4_t": "Sleep and energy reset",
  "plan.modules_h2": "Your plan covers what you picked",
  "plan.outcomes_h2": "In 30 days you said you want",
  "plan.rail_eyebrow": "Your plan",
  "plan.rail_length": "· 12 weeks",
  "plan.rail_proof": "men have run this plan. [Read what they said](#) — real reviews only.",
  "plan.rail_row1": "Daily commitment",
  "plan.rail_row1v": "10 minutes",
  "plan.rail_row2": "Modules selected",
  "plan.rail_row3": "First action",
  "plan.rail_row3v": "Tonight",
  "q:age:opt:0": "18–29",
  "q:age:opt:1": "30–39",
  "q:age:opt:2": "40–49",
  "q:age:opt:3": "50+",
  "q:age:sub": "Select your age to begin",
  "q:age:title": "The smartest way to get her back",
  "q:goal:note": "This becomes the name of your plan on the results page.",
  "q:goal:opt:0": "Get her back",
  "q:goal:opt:1": "Make her miss me",
  "q:goal:opt:2": "Rekindle the spark",
  "q:goal:opt:3": "Move on with confidence",
  "q:goal:title": "What do you want most right now?",
  "q:hardest_part:note": "It becomes the opening line of your results.",
  "q:hardest_part:opt:0": "I can't stop thinking about her",
  "q:hardest_part:opt:1": "I keep checking what she's doing",
  "q:hardest_part:opt:2": "I never know what to say",
  "q:hardest_part:opt:3": "I don't feel like myself",
  "q:hardest_part:sub": "Pick the one that's loudest today.",
  "q:hardest_part:title": "What's the hardest part right now?",
  "q:her_behaviour:note": "There's no wrong answer. Every option describes a kind of uncertainty the plan is built to resolve.",
  "q:her_behaviour:opt:0": "Hot and cold, hard to read",
  "q:her_behaviour:opt:1": "Cold and distant",
  "q:her_behaviour:opt:2": "Only messages when she needs something",
  "q:her_behaviour:opt:3": "Total silence",
  "q:her_behaviour:opt:4": "She's seeing someone else",
  "q:her_behaviour:title": "How is she acting since it ended?",
  "q:issues:note": "Each one maps to a module in the plan you see at the end.",
  "q:issues:opt:0": "Trust",
  "q:issues:opt:1": "Emotional distance",
  "q:issues:opt:2": "Different priorities",
  "q:issues:opt:3": "We argued too much",
  "q:issues:opt:4": "Outside interference",
  "q:issues:opt:5": "I stopped showing up",
  "q:issues:opt:6": "Something else",
  "q:issues:sub": "Choose all that apply",
  "q:issues:title": "What went wrong between you?",
  "q:outcomes:note": "These become the outcomes listed on your results page.",
  "q:outcomes:opt:0": "She's texting first",
  "q:outcomes:opt:1": "We're talking again",
  "q:outcomes:opt:2": "I've stopped overthinking",
  "q:outcomes:opt:3": "Back together",
  "q:outcomes:opt:4": "Sleeping properly",
  "q:outcomes:opt:5": "Fit and sharp again",
  "q:outcomes:sub": "Choose all that apply",
  "q:outcomes:title": "Where do you want to be in 30 days?",
  "q:readiness:note": "Be honest — this is the gap the plan closes first.",
  "q:readiness:opt:0": "No idea",
  "q:readiness:opt:1": "I'd probably get it wrong",
  "q:readiness:opt:2": "Roughly",
  "q:readiness:opt:3": "Yes",
  "q:readiness:title": "If she messaged you tonight, would you know what to say?",
  "q:slipped:note": "Physical things slip after a breakup. Saying which ones lets the plan run alongside the rest.",
  "q:slipped:opt:0": "Sleep",
  "q:slipped:opt:0:sub": "I'm awake at 3am",
  "q:slipped:opt:1": "Energy",
  "q:slipped:opt:1:sub": "Flat by mid-afternoon",
  "q:slipped:opt:2": "Training and drive",
  "q:slipped:opt:2:sub": "I've stopped showing up for myself",
  "q:slipped:opt:3": "Appetite",
  "q:slipped:opt:3:sub": "Eating badly or barely",
  "q:slipped:opt:4": "Nothing physical",
  "q:slipped:sub": "Choose all that apply",
  "q:slipped:title": "Since the breakup, which of these have slipped?",
  "q:status:note": "A one-tap opener. Whatever you pick, the next screen is the same — this shapes what your plan opens with, not where you go.",
  "q:status:opt:0": "Recently broke up",
  "q:status:opt:1": "Single",
  "q:status:opt:2": "It's complicated",
  "q:status:opt:3": "In a relationship",
  "q:status:opt:4": "Married",
  "q:status:title": "What's your current relationship status?",
  "q:time_since:note": "How recent it is decides what week one asks you to do first.",
  "q:time_since:opt:0": "Days ago",
  "q:time_since:opt:1": "A few weeks",
  "q:time_since:opt:2": "1–3 months",
  "q:time_since:opt:3": "More than 3 months",
  "q:time_since:opt:4": "It's complicated",
  "q:time_since:title": "How long ago did it end?",
  "q:who_ended:note": "The answer here changes the first line of your plan, not the plan itself.",
  "q:who_ended:opt:0": "She left",
  "q:who_ended:opt:1": "I walked away and regret it",
  "q:who_ended:opt:2": "It was mutual",
  "q:who_ended:title": "Who ended it?",
  "review1.body": "Week one was mostly about me, not about her. That turned out to be the part I had been getting wrong.",
  "review1.initials": "M T",
  "review1.meta": "Sample review",
  "review1.name": "Marcus T.",
  "review2.body": "The order was what made the difference. I had been doing roughly the right things at completely the wrong time.",
  "review2.initials": "D R",
  "review2.meta": "Sample review",
  "review2.name": "Daniel R.",
  "review3.body": "First time in two months I got through a whole day without checking her profile. That alone was worth it.",
  "review3.initials": "J O",
  "review3.meta": "Sample review",
  "review3.name": "James O.",
  "scratch.apply_step1": "Checking eligibility",
  "scratch.apply_step2": "Reserving your rate",
  "scratch.apply_step3": "Locking it in",
  "scratch.apply_step4": "Ready",
  "scratch.cta": "Scratch to continue",
  "scratch.done": "Discount locked to this session",
  "scratch.eyebrow": "One thing first",
  "scratch.h1": "Scratch to reveal your discount, {first_name}",
  "scratch.hint": "Drag across the panel to uncover it",
  "scratch.lede": "It applies automatically at checkout and holds for this session.",
  "scratch.modal_eyebrow": "One moment",
  "scratch.modal_title": "Reserving your discount",
  "scratch.pct": "{discount}%",
  "scratch.pct_sub": "off your first plan",
  "section.1": "Your situation",
  "section.2": "Her signals & your patterns",
  "section.3": "Readiness",
  "ui.continue": "Continue",
  "ui.selected": "{n} selected",
  "ui.tap_hint": "Tap an answer to continue",
};
